# Generated by Django 5.0.2 on 2024-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='item',
            field=models.CharField(max_length=50),
        ),
    ]
